const router=require('express').Router(); const auth=require('./auth.routes'); const home=require('../../controllers/api/home.controller'); const content=require('../../controllers/api/content.controller'); const providers=require('../../controllers/api/provider.controller'); const offerings=require('../../controllers/api/offering.controller'); const bookings=require('../../controllers/api/booking.controller'); const qr=require('../../controllers/api/qr.controller'); const {authenticateApi,authenticateProviderApi}=require('../../middleware/api-auth.middleware'); const {allowRoles}=require('../../middleware/role.middleware'); const {create}=require('../../validators/booking.validator'); const {validate}=require('../../middleware/validation.middleware'); const {qrLimiter}=require('../../middleware/rate-limit.middleware'); const asyncHandler=require('../../utils/asyncHandler'); const {body,param}=require('express-validator');
router.use('/auth',auth);
router.use('/dashboard',require('./dashboard.routes'));
router.get('/home',asyncHandler(home.home));
for (const resource of ['stories','news','events','safety-tips','weather']) { router.get(`/${resource}`,(req,_res,next)=>{req.params.resource=resource;next();},asyncHandler(content.list)); router.get(`/${resource}/:id`,(req,_res,next)=>{req.params.resource=resource;next();},asyncHandler(content.get)); }
router.get('/providers',asyncHandler(providers.list)); router.get('/providers/:id',asyncHandler(providers.get));
router.get('/offerings',asyncHandler(offerings.list)); router.get('/services',asyncHandler((req,res,next)=>{req.query.type='SERVICE';return offerings.list(req,res,next);})); router.get('/activities',asyncHandler((req,res,next)=>{req.query.type='ACTIVITY';return offerings.list(req,res,next);})); router.get('/offerings/:id',asyncHandler(offerings.get));
router.post('/bookings',authenticateApi,allowRoles('CUSTOMER'),create,validate,asyncHandler(bookings.create)); router.get('/bookings',authenticateApi,allowRoles('CUSTOMER'),asyncHandler(bookings.list)); router.get('/bookings/:id',authenticateApi,allowRoles('CUSTOMER'),param('id').isInt(),validate,asyncHandler(bookings.get)); router.post('/bookings/:id/cancel',authenticateApi,allowRoles('CUSTOMER'),param('id').isInt(),validate,asyncHandler(bookings.cancel)); router.get('/bookings/:bookingId/participants/:participantId/qr',authenticateApi,allowRoles('CUSTOMER'),asyncHandler(qr.participantQr));
router.post('/provider/qr/validate',authenticateProviderApi,allowRoles('PROVIDER'),qrLimiter,body('token').trim().notEmpty().withMessage('token is required'),validate,asyncHandler(qr.validateProvider)); module.exports=router;
