const router=require('express').Router(); const express=require('express'); const path=require('path'); const auth=require('./auth.routes'); const home=require('../../controllers/api/home.controller'); const content=require('../../controllers/api/content.controller'); const providers=require('../../controllers/api/provider.controller'); const offerings=require('../../controllers/api/offering.controller'); const bookings=require('../../controllers/api/booking.controller'); const qr=require('../../controllers/api/qr.controller'); const {authenticateApi,authenticateProviderApi}=require('../../middleware/api-auth.middleware'); const {allowRoles}=require('../../middleware/role.middleware'); const {create}=require('../../validators/booking.validator'); const {validate}=require('../../middleware/validation.middleware'); const {qrLimiter}=require('../../middleware/rate-limit.middleware'); const asyncHandler=require('../../utils/asyncHandler'); const {body,param}=require('express-validator');
router.use('/uploads', express.static(path.join(__dirname, '../../public/uploads')));
router.use('/auth',auth);
router.use('/dashboard',require('./dashboard.routes'));
router.get('/home',asyncHandler(home.home));
for (const resource of ['stories','news','events','restaurants','safety-tips','weather']) { router.get(`/${resource}`,(req,_res,next)=>{req.params.resource=resource;next();},asyncHandler(content.list)); router.get(`/${resource}/:id`,(req,_res,next)=>{req.params.resource=resource;next();},asyncHandler(content.get)); }
router.get('/providers',asyncHandler(providers.list)); router.get('/providers/:id',asyncHandler(providers.get));
router.get('/offerings',asyncHandler(offerings.list)); router.get('/services',asyncHandler((req,res,next)=>{req.query.type='SERVICE';return offerings.list(req,res,next);})); router.get('/activities',asyncHandler((req,res,next)=>{req.query.type='ACTIVITY';return offerings.list(req,res,next);})); router.get('/offerings/:id',asyncHandler(offerings.get));
router.post('/bookings',authenticateApi,allowRoles('CUSTOMER','ADMIN','PROVIDER'),create,validate,asyncHandler(bookings.create)); router.get('/bookings',authenticateApi,allowRoles('CUSTOMER','ADMIN','PROVIDER'),asyncHandler(bookings.list)); router.get('/bookings/:id',authenticateApi,allowRoles('CUSTOMER','ADMIN','PROVIDER'),param('id').isInt(),validate,asyncHandler(bookings.get)); router.post('/bookings/:id/cancel',authenticateApi,allowRoles('CUSTOMER','ADMIN','PROVIDER'),param('id').isInt(),validate,asyncHandler(bookings.cancel)); router.get('/bookings/:bookingId/participants/:participantId/qr',authenticateApi,allowRoles('CUSTOMER','ADMIN','PROVIDER'),asyncHandler(qr.participantQr));
router.post('/provider/qr/validate',authenticateProviderApi,allowRoles('PROVIDER'),qrLimiter,body('token').trim().notEmpty().withMessage('token is required'),validate,asyncHandler(qr.validateProvider));
router.get('/privacy-policy',asyncHandler(async(_req,res)=>{const settingRepo=require('../../repositories/setting.repository');const content=(await settingRepo.get('privacy_policy_content'))||'Welcome to Zeera. Your privacy is paramount to us.';res.json({success:true,data:{content}});}));
module.exports=router;
