const crypto = require('crypto'); const { transaction, query } = require('../config/database'); const AppError = require('../utils/AppError'); const offeringRepo = require('../repositories/offering.repository'); const bookingRepo = require('../repositories/booking.repository'); const { normalizePhone } = require('../utils/phone'); const { randomToken } = require('../utils/token'); const { validityWindow } = require('../utils/date'); const { qrValiditySettings } = require('./setting.service'); const { publicUrl } = require('../utils/qr'); const { totalForParticipants } = require('../utils/booking'); const { getPagination, limitOffsetClause } = require('../utils/pagination');
const code = () => `ZR-${new Date().getUTCFullYear()}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;
function withUrls(participants) { return participants.map((participant) => ({ ...participant, qr: participant.public_token ? { id: participant.qr_id, status: participant.qr_status, valid_from: participant.valid_from, valid_until: participant.valid_until, used_at: participant.used_at, expired_reason: participant.expired_reason, public_url: publicUrl(participant.public_token) } : null })); }
async function create(customer, input) {
  const extras = Array.isArray(input.participants) ? input.participants : []; const participantData = [];
  if (input.include_customer === true) participantData.push({ fullName: customer.full_name, phone: customer.phone, isOwner: true });
  for (const item of extras) { const phone = normalizePhone(item.phone); if (!String(item.full_name || '').trim() || !phone) throw new AppError('Each participant requires a valid name and phone number', 422, 'VALIDATION_ERROR'); participantData.push({ fullName: item.full_name.trim(), phone, isOwner: false }); }
  if (!participantData.length) throw new AppError('At least one participant is required',422,'NO_PARTICIPANTS');
  const settings = await qrValiditySettings();
  const booking = await transaction(async (connection) => {
    const offering = await offeringRepo.find(input.offering_id, connection, true);
    if (!offering || !offering.is_active || !offering.provider_is_active) throw new AppError('Offering is unavailable',404,'OFFERING_NOT_FOUND');
    const unitPrice = input.currency === 'USD' ? offering.price_usd : offering.price_lbp;
    const bookingCode = code(); const insert = await connection.execute('INSERT INTO bookings (booking_code,customer_user_id,offering_id,scheduled_at,currency,unit_price,participant_count,total_amount,notes) VALUES (?,?,?,?,?,?,?,?,?)',[bookingCode,customer.id,offering.id,input.scheduled_at,input.currency,unitPrice,participantData.length,totalForParticipants(unitPrice,participantData.length),input.notes?.trim() || null]);
    const bookingId = insert[0].insertId; const validity = validityWindow(input.scheduled_at,settings.before,settings.after);
    for (const person of participantData) { const participant = await connection.execute('INSERT INTO booking_participants (booking_id,full_name,phone,is_owner) VALUES (?,?,?,?)',[bookingId,person.fullName,person.phone,person.isOwner]); await connection.execute('INSERT INTO participant_qr_codes (participant_id,public_token,status,valid_from,valid_until) VALUES (?,?,?,?,?)',[participant[0].insertId,randomToken(), 'ACTIVE',validity.validFrom,validity.validUntil]); }
    return bookingId;
  }); return getForCustomer(booking, customer.id);
}
async function getForCustomer(id, customerId) { const booking = await bookingRepo.find(id); if (!booking || booking.customer_user_id !== Number(customerId)) throw new AppError('Booking not found',404,'BOOKING_NOT_FOUND'); return { ...booking, participants: withUrls(await bookingRepo.participantRows(id)) }; }
async function listForCustomer(customerId, pagination = {}) { const { page, limit, offset } = getPagination(pagination); const [items,count]=await Promise.all([query(`SELECT b.*,o.title AS offering_title,o.type AS offering_type,p.business_name AS provider_name FROM bookings b JOIN offerings o ON o.id=b.offering_id JOIN providers p ON p.id=o.provider_id WHERE b.customer_user_id=? ORDER BY b.created_at DESC ${limitOffsetClause(limit, offset)}`,[customerId]),query('SELECT COUNT(*) AS total FROM bookings WHERE customer_user_id=?',[customerId])]); return { items, pagination:{page,limit,total:count[0].total,pages:Math.ceil(count[0].total/limit)} }; }
async function cancel(id, customerId) { await transaction(async (connection)=> { const booking=await bookingRepo.find(id,connection,true); if (!booking || booking.customer_user_id !== Number(customerId)) throw new AppError('Booking not found',404,'BOOKING_NOT_FOUND'); if (!['PENDING','CONFIRMED'].includes(booking.status)) throw new AppError('This booking cannot be cancelled',422,'BOOKING_NOT_CANCELLABLE'); await connection.execute("UPDATE bookings SET status='CANCELLED' WHERE id=?",[id]); await connection.execute("UPDATE participant_qr_codes q JOIN booking_participants p ON p.id=q.participant_id SET q.status='CANCELLED',q.expired_reason='BOOKING_CANCELLED' WHERE p.booking_id=? AND q.status='ACTIVE'",[id]); }); return getForCustomer(id,customerId); }
module.exports = { create, getForCustomer, listForCustomer, cancel, withUrls };
