import { z } from 'zod';
export type FieldType='text'|'textarea'|'datetime-local'|'date'|'time'|'number'|'select'|'checkbox'|'file'|'tel';export interface Field{name:string;label:string;type:FieldType;required?:boolean;options?:readonly string[];multiple?:boolean;}
export interface ResourceMeta{title:string;fields:Field[];readonly?:boolean;schema:z.ZodType<Record<string,unknown>>;}
const content=z.object({title:z.string().min(1,'Title is required'),content:z.string().min(1,'Content is required')}).passthrough();const image=z.instanceof(File).optional();
const active:Field={name:'is_active',label:'Active',type:'checkbox'};
const definitions:Record<string,ResourceMeta>={
  stories:{title:'Stories',fields:[{name:'title',label:'Title',type:'text',required:true},{name:'content',label:'Content',type:'textarea',required:true},{name:'image',label:'Image',type:'file',required:true},{name:'story_time',label:'Story time',type:'datetime-local',required:true},active],schema:content.extend({story_time:z.string().min(1,'Story time is required'),image}).passthrough()},
  news:{title:'News',fields:[{name:'title',label:'Title',type:'text',required:true},{name:'content',label:'Content',type:'textarea',required:true},{name:'image',label:'Image',type:'file',required:true},{name:'published_at',label:'Published at',type:'datetime-local',required:true},active],schema:content.extend({published_at:z.string().min(1,'Published date is required'),image}).passthrough()},
  events:{title:'Events',fields:[{name:'title',label:'Title',type:'text',required:true},{name:'description',label:'Description',type:'textarea',required:true},{name:'image',label:'Image',type:'file',required:true},{name:'event_date',label:'Event date',type:'date',required:true},{name:'start_time',label:'Start time',type:'time'},{name:'end_time',label:'End time',type:'time'},{name:'location',label:'Location',type:'text'},active],schema:z.object({title:z.string().min(1),description:z.string().min(1),event_date:z.string().min(1,'Event date is required'),image}).passthrough()},
  restaurants:{title:'Restaurants',fields:[{name:'name',label:'Name',type:'text',required:true},{name:'description',label:'Description',type:'textarea',required:true},{name:'cuisine_type',label:'Cuisine type',type:'text',required:true},{name:'image',label:'Image',type:'file'},{name:'opening_time',label:'Opening time',type:'text'},{name:'closing_time',label:'Closing time',type:'text'},{name:'location',label:'Location',type:'text'},{name:'phone',label:'Phone',type:'tel'},{name:'rating',label:'Rating',type:'number'},{name:'price_range',label:'Price range',type:'text'},{name:'menu_items',label:'Menu items (JSON)',type:'textarea'},active],schema:z.object({name:z.string().min(1,'Name is required'),description:z.string().min(1,'Description is required'),cuisine_type:z.string().min(1,'Cuisine type is required'),image}).passthrough()},
  'safety-tips':{title:'Safety tips',fields:[{name:'title',label:'Title',type:'text',required:true},{name:'content',label:'Content',type:'textarea',required:true},{name:'image',label:'Image',type:'file'},active],schema:content.passthrough()},
  providers:{title:'Providers',fields:[{name:'business_name',label:'Business / Establishment Name',type:'text',required:true},{name:'description',label:'Description',type:'textarea'},{name:'phone',label:'Phone',type:'tel',required:true},{name:'email',label:'Email',type:'text'},{name:'address',label:'Address',type:'text'},{name:'user_id',label:'Primary Contact / Owner (Optional)',type:'select'},{name:'logo',label:'Logo',type:'file'},{name:'cover_image',label:'Cover image',type:'file'},active],schema:z.object({business_name:z.string().min(1),phone:z.string().min(7)}).passthrough()},
  'provider-users':{title:'Provider users',fields:[{name:'full_name',label:'Full name',type:'text',required:true},{name:'phone',label:'Phone',type:'tel',required:true},{name:'provider_id',label:'Assigned Provider Place',type:'select'},{name:'password',label:'Password (leave blank to keep current)',type:'text'},active],schema:z.object({full_name:z.string().min(2),phone:z.string().min(7),provider_id:z.string().optional().or(z.literal('')),password:z.string().optional().or(z.literal(''))}).passthrough()},
  offerings:{title:'Offerings',fields:[{name:'provider_id',label:'Provider',type:'select',required:true},{name:'type',label:'Type',type:'select',required:true,options:['SERVICE','ACTIVITY']},{name:'title',label:'Title',type:'text',required:true},{name:'description',label:'Description',type:'textarea',required:true},{name:'image',label:'Image',type:'file',required:true},{name:'price_usd',label:'Price USD',type:'number',required:true},{name:'price_lbp',label:'Price LBP',type:'number',required:true},{name:'duration_minutes',label:'Duration minutes',type:'number'},{name:'capacity',label:'Capacity',type:'number'},{name:'location',label:'Location',type:'text'},active],schema:z.object({provider_id:z.string().min(1),type:z.enum(['SERVICE','ACTIVITY']),title:z.string().min(1),description:z.string().min(1),price_usd:z.coerce.number().min(0),price_lbp:z.coerce.number().min(0),image}).passthrough()},
  customers:{title:'Customers',fields:[{name:'full_name',label:'Full name',type:'text',required:true},{name:'phone',label:'Phone',type:'tel',required:true},{name:'password',label:'New Password (optional)',type:'text'},active],schema:z.object({full_name:z.string().min(2,'Full name is required'),phone:z.string().min(7,'Phone number is invalid'),password:z.string().optional().or(z.literal(''))}).passthrough()},
  users:{title:'All Users',fields:[{name:'full_name',label:'Full name',type:'text',required:true},{name:'phone',label:'Phone',type:'tel',required:true},{name:'role',label:'Role',type:'select',required:true,options:['CUSTOMER','PROVIDER','ADMIN']},{name:'provider_id',label:'Assigned Provider Place (For Providers)',type:'select'},{name:'password',label:'New Password (optional)',type:'text'},active],schema:z.object({full_name:z.string().min(2,'Full name is required'),phone:z.string().min(7,'Phone number is invalid'),role:z.enum(['CUSTOMER','PROVIDER','ADMIN']),provider_id:z.string().optional().or(z.literal('')),password:z.string().optional().or(z.literal(''))}).passthrough()},
  bookings:{title:'Bookings',fields:[],readonly:true,schema:z.object({}).passthrough()},participants:{title:'Participants',fields:[],readonly:true,schema:z.object({}).passthrough()},'qr-codes':{title:'QR codes',fields:[],readonly:true,schema:z.object({}).passthrough()},'scan-logs':{title:'Scan logs',fields:[],readonly:true,schema:z.object({}).passthrough()},settings:{title:'Settings',fields:[{name:'setting_key',label:'Setting',type:'text',required:true},{name:'setting_value',label:'Value',type:'textarea',required:true}],schema:z.object({setting_key:z.string().min(1),setting_value:z.string().min(1)}).passthrough()},'privacy-policy':{title:'Privacy Policy',fields:[],readonly:true,schema:z.object({}).passthrough()},'deletion-requests':{title:'Deletion Requests',fields:[{name:'phone',label:'Phone',type:'text',required:true},{name:'full_name',label:'Full Name',type:'text'},{name:'reason',label:'Reason',type:'textarea'},{name:'status',label:'Status',type:'select',required:true,options:['PENDING','PROCESSED','REJECTED']}],schema:z.object({phone:z.string().min(1),full_name:z.string().optional(),reason:z.string().optional(),status:z.enum(['PENDING','PROCESSED','REJECTED'])}).passthrough()}
};
export function meta(name:string){return definitions[name] || definitions.stories;}
export const resources=Object.keys(definitions);
