import { z } from 'zod';
export type FieldType='text'|'textarea'|'datetime-local'|'date'|'time'|'number'|'select'|'checkbox'|'file'|'tel';export interface Field{name:string;label:string;type:FieldType;required?:boolean;options?:readonly string[];multiple?:boolean;}
export interface ResourceMeta{title:string;fields:Field[];readonly?:boolean;schema:z.ZodType<Record<string,unknown>>;}
const content=z.object({title:z.string().min(1,'Title is required'),content:z.string().min(1,'Content is required')}).passthrough();const image=z.instanceof(File).optional();
const active:Field={name:'is_active',label:'Active',type:'checkbox'};
const definitions:Record<string,ResourceMeta>={
  stories:{title:'Stories',fields:[{name:'title',label:'Title',type:'text',required:true},{name:'content',label:'Content',type:'textarea',required:true},{name:'image',label:'Image',type:'file',required:true},{name:'story_time',label:'Story time',type:'datetime-local',required:true},active,{name:'display_order',label:'Display order',type:'number'}],schema:content.extend({story_time:z.string().min(1,'Story time is required'),image}).passthrough()},
  news:{title:'News',fields:[{name:'title',label:'Title',type:'text',required:true},{name:'content',label:'Content',type:'textarea',required:true},{name:'image',label:'Image',type:'file',required:true},{name:'published_at',label:'Published at',type:'datetime-local',required:true},active],schema:content.extend({published_at:z.string().min(1,'Published date is required'),image}).passthrough()},
  events:{title:'Events',fields:[{name:'title',label:'Title',type:'text',required:true},{name:'description',label:'Description',type:'textarea',required:true},{name:'image',label:'Image',type:'file',required:true},{name:'event_date',label:'Event date',type:'date',required:true},{name:'start_time',label:'Start time',type:'time'},{name:'end_time',label:'End time',type:'time'},{name:'location',label:'Location',type:'text'},active],schema:z.object({title:z.string().min(1),description:z.string().min(1),event_date:z.string().min(1,'Event date is required'),image}).passthrough()},
  'safety-tips':{title:'Safety tips',fields:[{name:'title',label:'Title',type:'text',required:true},{name:'content',label:'Content',type:'textarea',required:true},{name:'image',label:'Image',type:'file'},active,{name:'display_order',label:'Display order',type:'number'}],schema:content.passthrough()},
  weather:{title:'Weather',fields:[{name:'location',label:'Location',type:'text',required:true},{name:'temperature',label:'Temperature',type:'number',required:true},{name:'condition',label:'Condition',type:'text',required:true},{name:'description',label:'Description',type:'textarea',required:true},{name:'humidity',label:'Humidity',type:'number'},{name:'wind_speed',label:'Wind speed',type:'number'},{name:'weather_date',label:'Weather date',type:'datetime-local',required:true},{name:'icon',label:'Icon URL',type:'text'},active],schema:z.object({location:z.string().min(1),temperature:z.coerce.number(),condition:z.string().min(1),description:z.string().min(1),weather_date:z.string().min(1)}).passthrough()},
  providers:{title:'Providers',fields:[{name:'user_id',label:'Provider user',type:'select',required:true},{name:'business_name',label:'Business name',type:'text',required:true},{name:'description',label:'Description',type:'textarea'},{name:'phone',label:'Phone',type:'tel',required:true},{name:'email',label:'Email',type:'text'},{name:'address',label:'Address',type:'text'},{name:'logo',label:'Logo',type:'file'},{name:'cover_image',label:'Cover image',type:'file'},active],schema:z.object({user_id:z.string().min(1),business_name:z.string().min(1),phone:z.string().min(7)}).passthrough()},
  'provider-users':{title:'Provider users',fields:[{name:'full_name',label:'Full name',type:'text',required:true},{name:'phone',label:'Phone',type:'tel',required:true},{name:'password',label:'Password',type:'text',required:true},active],schema:z.object({full_name:z.string().min(2),phone:z.string().min(7),password:z.string().min(8).optional()}).passthrough()},
  offerings:{title:'Offerings',fields:[{name:'provider_id',label:'Provider',type:'select',required:true},{name:'type',label:'Type',type:'select',required:true,options:['SERVICE','ACTIVITY']},{name:'title',label:'Title',type:'text',required:true},{name:'description',label:'Description',type:'textarea',required:true},{name:'image',label:'Image',type:'file',required:true},{name:'price_usd',label:'Price USD',type:'number',required:true},{name:'price_lbp',label:'Price LBP',type:'number',required:true},{name:'duration_minutes',label:'Duration minutes',type:'number'},{name:'capacity',label:'Capacity',type:'number'},{name:'location',label:'Location',type:'text'},active],schema:z.object({provider_id:z.string().min(1),type:z.enum(['SERVICE','ACTIVITY']),title:z.string().min(1),description:z.string().min(1),price_usd:z.coerce.number().min(0),price_lbp:z.coerce.number().min(0),image}).passthrough()},
  customers:{title:'Customers',fields:[],readonly:true,schema:z.object({}).passthrough()},bookings:{title:'Bookings',fields:[],readonly:true,schema:z.object({}).passthrough()},participants:{title:'Participants',fields:[],readonly:true,schema:z.object({}).passthrough()},'qr-codes':{title:'QR codes',fields:[],readonly:true,schema:z.object({}).passthrough()},'scan-logs':{title:'Scan logs',fields:[],readonly:true,schema:z.object({}).passthrough()},settings:{title:'Settings',fields:[{name:'setting_key',label:'Setting',type:'text',required:true},{name:'setting_value',label:'Value',type:'textarea',required:true}],schema:z.object({setting_key:z.string().min(1),setting_value:z.string().min(1)}).passthrough()}
};
export function meta(name:string){return definitions[name] || definitions.stories;}
export const resources=Object.keys(definitions);
